# Generated by Django 3.2 on 2021-04-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210414_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='content',
            field=models.TextField(default='lai lai ', max_length=5000),
            preserve_default=False,
        ),
    ]
